name: yTwhisper
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2
  - ffmpeg
  - ffmpeg-python
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - yt-dlp
  - pip:
    - openai-whisper
